name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - working-directory: views
        run: |
          yarn install
          yarn build

          cp -R -t build ../act_ws.py ../gbfr_act/utils/hook/EasyHook64.dll ../uac_start.cmd ../steam_win_start.cmd ../gbfr_act
          mv build gbfr-parser.${{ inputs.tag }}
          zip -r gbfr-parser.${{ inputs.tag }}.zip.rename gbfr-parser.${{ inputs.tag }}
          cp gbfr-parser.${{ inputs.tag }}.zip.rename gbfr-parser.${{ inputs.tag }}.zip

      - run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
          file: views/gbfr-parser.${{ inputs.tag }}.zip
          asset_name: gbfr-parser.${{ inputs.tag }}.zip
          overwrite: true

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
          file: views/gbfr-parser.${{ inputs.tag }}.zip.rename
          asset_name: gbfr-parser.${{ inputs.tag }}.zip.rename
          overwrite: true
